### ISSUE TITLE
DBSCANCellX_Testdata_Figure4.csv Formatting

### ISSUE THREAD

**Issue by saralichtarge** [PasLukas/DBSCAN-CellX#1]
I’m trying to recreate results from Figure 4. In the “DBSCANCellX_Testdata_Figure4.csv” file, there are four column names, but each row contains eight values. While the first two values per row can be disregarded due to indexing, I’m unsure how to interpret the extra two values. Could you clarify the intended reading of this table?

**Comment by LeonieKuechenhoff** [comment]
Thank you for your interest in our package. Sorry for the confusion; I have to admit that the test file can be a little confusing. As you rightly guessed, the first column is the index. The second column is the image number, the file contains the data from three images, hence these values are either 1, 2, or 3. The third column is the cell id, each cell in each image has a unique ID. Then come the X and Y coordinates - they have a comma as a decimal separator, I think here your confusion regarding the extra columns came in. The density refers to the seeding density we used in cell culture.

To make it more clear, here are all the values from the first line in the file as an example:

"1"; --> index
1; --> image ID
"1"; --> cell ID
2076,96688741721; --> X coordinate, separated by comma as a decimal sep
5,30684326710816; --> Y coordinate, separated by comma as a decimal sep
"10k" --> seeding density

I hope this helped!

**Comment by saralichtarge** [comment]
Awesome, thank you for your input! You were right, the comma as a decimal separator is what threw me off -- hazard of collaborating across continents :)
